name: Tests

on:
  pull_request:
    branches:
      - main

jobs:

#   swiftlang_tests:
#     name: Swiftlang Tests
#     uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
#     with:
#       enable_windows_checks : false
#       linux_build_command: "swift test --parallel --enable-code-coverage"
#       linux_exclude_swift_versions: "[{\"swift_version\": \"5.8\"}, {\"swift_version\": \"5.9\"}, {\"swift_version\": \"5.10\"}, {\"swift_version\": \"nightly\"}, {\"swift_version\": \"nightly-main\"}, {\"swift_version\": \"nightly-6.0\"}, {\"swift_version\": \"nightly-6.1\"}]"